apiVersion: v1
kind: Service
metadata:
  name: guest-app
  labels:
    name: guestbook-service
    app: guestbook-app
  spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3000
    selector:
      name: guest-pod
      app: guestbook-app
