apiVersion: apps/v1
kind: Deployment
metadata:
  name: guest-app-deployment
  labels:
    app: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      name: guest-pod
      app: guestbook-app

  template:
    metadata:
      name: guest-pod
      labels:
        name: guest-pod
        app: guestbook-app
    spec:
      containers:
      - name: guestapp
        image: kubernetes/guestbook:v2
        ports:
        - containerPort: 3000
